#%RAML 1.0
title: puncho API
version: 0.1
baseUri: http://ec2-3-15-172-128.us-east-2.compute.amazonaws.com
documentation:
  - title: Welcome
    content: |
      Welcome to the puncho API Documentation.

/user: # optional resource
  description: This is the top level description for /users.

  post:
      description: create a new user
      body:
        application/json:
          properties:
            name:
              description: user object
              type: object
              example:
                {
                    "firstname": "user1",
                    "lastname": "user1",
                    "email": "a@b.c",
                    "password_hash": "hashxyz"
                }
      responses:
        201: #USER CREATED
          body:
            application/json:
              properties:
                name:
                  description: user object
                  type: object
                  example:
                    {
                        "firstname": "user1",
                        "lastname": "user1",
                        "email": "a@b.c"
                    }
        409: #EMAIL EXISTS
          body:
            text/plain:
              example: "email exists already"
  /login:
    description: login user
    post:
      body:
        application/json:
          properties:
            name:
              description: user object
              type: object
              example:
                {
                    "email": "a@b.c",
                    "password_hash": "hashxyz"
                }
      responses:
        200:
          body:
            application/json:
              properties:
                name:
                  description: user object
                  type: object
                  example:
                    {
                        "firstname": "user1",
                        "lastname": "user1",
                        "email": "a@b.c"
                    }
        401:
          body:
            text/plain:
              example: "bad credentials"
        401:
          body:
            text/plain:
              example: "email not found"

  /details:
    /{user_id}:
      get:
        responses:
            200:
              body:
                application/json:
                  properties:
                    name:
                      description: user object
                      type: object
                      example:
                        {
                            "firstname": "user1",
                            "lastname": "user1",
                            "email": "a@b.c"
                        }


/workout:
  description: This is the top level description for /workouts.

  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
            type: | # structural definition of a response (schema or type)
              {
                "title": "get collection of all workouts",
                "type": "array"
              }
            example: # example how a response looks like
              {
                "workouts":
                [
                    {
                      "id": 0,
                      "title": "some_title",
                      "description": "some_description",
                      "start_time": "2019/8/8/14:00",
                      "end_time": "2019/8/8/15:00",
                      "w_type": "punchbag"
                    },
                    ...
                ]
              }
  /summary:
    get:
        uriParameters:
          user_id:
            type: string
            description: user id
            minLength: 1
            maxLength: 10
          workout_id:
            type: string
            description: workout id
            minLength: 1
            maxLength: 10
        description: get summary of some user's specific workout
        responses:
            200:
              body:
                application/json:
                  properties:
                    name:
                      description: summary object
                      type: object
                      example:
                        {
                            "name": "workout x",
                            "start_time": "2019/8/8/14:00",
                            "w_type": "punchbag",
                            "avg_hr": "99",
                            "max_hr": "150",
                            "kcals": "339",
                            "punch_score": "12341"
                        }
/booking:
  /{user_id}:
    get:
        responses:
            200:
                body:
                    array:
                        type:
                            {
                                "title": "get list of all workout ids for specific user id - list of ids of all workouts the user is registered to",
                                "type": "array"
                            }
                        example:
                            [
                              {
                                "id": 0
                              },
                              {
                                "id": 1
                              }
                            ]
  post:
    description: create a new booking
    body:
      application/json:
        properties:
          name:
            description: booking object
            type: object
            example:
              {
                  "user_id": "1",
                  "workout_id": "1"
              }
    responses:
      201: #BOOKING CREATED
        body:
          application/json:
            properties:
              name:
                description: booking object
                type: object
                example:
                  {
                      "user_id": "1",
                      "workout_id": "1"
                  }
      409: #BOOKING FAILED
        body:
          text/plain:
            example: "workout full"

/punches:
  /{user_id}:
    get:
        responses:
            200:
                body:
                    array:
                        type:
                            {
                                "title": "get list of all punchesfor specific user id",
                                "type": "array"
                            }
                        example:
                            [
                              {
                                "force": 0
                              },
                              {
                                "force": 1
                              }
                            ]
  /score/{user_id}:
    get:
        responses:
            200:
                body:
                    string:
                        example:
                            "1000"
/hr:
  /latest/{user_id}:
    get:
        descrpiption: get instantaneous heart rate
        responses:
          200:
            body:
              application/json:
                properties:
                  name:
                    description: object with hr data
                    type: object
                    example:
                      {
                          "hr": "100",
                          "kcals": "30"
                      }
  /avg/{user_id}:
    get:
        description: get current average heart rate
        responses:
            200:
                body:
                    string:
                        example:
                            "100"

/weigh_in:
  /{user_id}:
    get:
        responses:
            200:
                body:
                    array:
                        type:
                            {
                                "title": "get list of all weigh ins specific user id",
                                "type": "array"
                            }
                        example:
                            [
                              {
                                "data": "TBD"
                              },
                              {
                                "data": "TBD"
                              }
                            ]
